# Generated by Django 2.2.1 on 2019-07-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=200)),
                ('Imagen', models.CharField(max_length=255)),
                ('Precio', models.FloatField()),
                ('Cantidad', models.TextField()),
            ],
        ),
    ]
