# Generated by Django 2.2.1 on 2019-07-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Imagen',
            field=models.TextField(),
        ),
    ]
